# ============================================================================
# STAGE 1: BUILD ENVIRONMENT
# ============================================================================
FROM node:22-alpine AS builder

LABEL "language"="nodejs"
LABEL "framework"="nuxt.js"

WORKDIR /src

# Copy package config safely (wildcard protects against missing lockfiles)
COPY package.json package-lock.json* ./

# Install all build-time dependencies 
RUN npm install

# Copy source code assets
COPY . .

# FORCE Nuxt to build a traditional standalone server directory (.output)
# This prevents it from building custom cloud/serverless directories
ENV NITRO_PRESET=node-server
ENV NODE_ENV=production

RUN npm run build

# ============================================================================
# STAGE 2: PRODUCTION RUNTIME BOUNDARY
# ============================================================================
FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=8080
ENV HOST=0.0.0.0

# Copy package configuration files safely
COPY package.json package-lock.json* ./

# Clean installation of production-only modules
RUN npm install --production

# ✅ FIXED PATH: Copies from the guaranteed standalone .output folder generated by the preset above
COPY --from=builder /src/.output ./.output

EXPOSE 8080

ENTRYPOINT ["node"]
CMD [".output/server/index.mjs"]
