// ============================================================================
// FILE: /composables/use-auth.ts - CIRCULAR DEPENDENCY FIXED
// ============================================================================
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { useNuxtApp, navigateTo } from '#app'
import { useSupabaseClient } from '~/composables/useSupabaseClient'

export const useAuth = () => {
  const router = useRouter()
  const supabase = useSupabaseClient()
  const nuxtApp = useNuxtApp()

  const loading = ref(false)
  const error = ref<string | null>(null)

  // ✅ LAZY IMPORT: Stores are imported inside functions, not at module level
  const getAuthStore = async () => {
    const { useAuthStore } = await import('~/stores/auth')
    return useAuthStore()
  }

  const getProfileStore = async () => {
    const { useProfileStore } = await import('~/stores/profile')
    return useProfileStore()
  }

  const cleanTokenString = (token: string | null): string | null => {
    if (!token || token === 'undefined' || token === 'null') return null
    return token.trim().replace(/^[\"']|[\"']$/g, '')
  }

  const executeProfileInitializationRoute = async () => {
    if (nuxtApp && typeof (nuxtApp as any).$initializeProfile === 'function') {
      await (nuxtApp as any).$initializeProfile()
    } else {
      const profileStore = await getProfileStore()
      if (profileStore && typeof (profileStore as any).initializeProfile === 'function') {
        await (profileStore as any).initializeProfile()
      }
    }
  }

  const clearSessionContext = async () => {
    if (process.client) {
      localStorage.removeItem('auth_token')
      localStorage.removeItem('auth_refresh_token')
      localStorage.removeItem('auth_user')
      localStorage.removeItem('auth_user_id')
      localStorage.removeItem('auth_remember_me')

      // legacy keys
      localStorage.removeItem('sb-access-token')
      localStorage.removeItem('sb-refresh-token')

      const keys = Object.keys(localStorage)
      keys.forEach((key) => {
        if (key.includes('supabase.auth.token') || key.startsWith('sb-') || key.startsWith('profile_data')) {
          localStorage.removeItem(key)
        }
      })
    }

    const authStore = await getAuthStore()
    const profileStore = await getProfileStore()
    
    authStore.clearAuth()
    profileStore.clearProfile()
    if (profileStore.clearAllProfileCache) {
      profileStore.clearAllProfileCache()
    }
  }

  const initializeUserSession = async () => {
    loading.value = true
    error.value = null
    try {
      const authStore = await getAuthStore()
      const profileStore = await getProfileStore()

      if (!authStore.isHydrated) {
        await authStore.hydrateFromStorage()
      }

      const { data: { session }, error: sessionError } = await supabase.auth.getSession()
      if (sessionError) throw sessionError

      if (session?.user && session?.access_token) {
        const sanitizedToken = cleanTokenString(session.access_token)
        if (!sanitizedToken) throw new Error('Invalid token format generated by provider session.')

        authStore.setToken(sanitizedToken)
        authStore.setUser(session.user)

        await profileStore.fetchProfile()
        await executeProfileInitializationRoute()
        return
      }

      // Fallback to existing local session
      if (authStore.token && authStore.userId) {
        await profileStore.fetchProfile()
      }
    } catch (err: any) {
      console.error('[useAuth] Session recovery failed:', err)
      error.value = err?.message || 'Failed to sync your credentials session.'
      await clearSessionContext()
    } finally {
      loading.value = false
    }
  }

  const signUp = async (email: string, password: string, options: any = {}) => {
    loading.value = true
    error.value = null
    try {
      const authStore = await getAuthStore()
      const profileStore = await getProfileStore()

      const { data, error: signUpError } = await supabase.auth.signUp({
        email,
        password,
        options: {
          emailRedirectTo: `${window.location.origin}/confirm`,
          ...options
        }
      })

      if (signUpError) throw signUpError

      // If provider returns immediate session
      if (data?.session?.access_token && data?.session?.user) {
        const sanitizedToken = cleanTokenString(data.session.access_token)
        if (sanitizedToken) {
          authStore.setToken(sanitizedToken)
          authStore.setUser(data.session.user)
          await profileStore.fetchProfile()
          await executeProfileInitializationRoute()
        }
      }

      return data
    } catch (err: any) {
      console.error('[useAuth] Registration failed:', err)
      error.value = err?.message || 'An error occurred during account creation.'
      throw err
    } finally {
      loading.value = false
    }
  }

  const signIn = async (email: string, password: string) => {
    loading.value = true
    error.value = null

    try {
      const authStore = await getAuthStore()
      const profileStore = await getProfileStore()

      // Hard reset stale session first (prevents cross-account bleed)
      await clearSessionContext()

      const response: any = await $fetch('/api/auth/login', {
        method: 'POST',
        body: { email, password }
      })

      if (!response?.token || !response?.user?.id) {
        throw new Error('Invalid login response payload')
      }

      // 1) set auth identity first
      authStore.setToken(response.token)
      authStore.setUser(response.user)

      // optional refresh token support
      if (response.refreshToken) {
        authStore.setRefreshToken(response.refreshToken)
      }

      // 2) never set profile directly from login user blob
      // fetch authoritative profile from /api/profile/me
      const fetched = await profileStore.fetchProfile()

      // 3) if profile missing, allow setup route flow
      const profileComplete = !!(fetched?.profile_completed && fetched?.username && fetched?.full_name)

      const redirectTo = response.redirectTo
        || (profileComplete ? '/feed' : '/profile/setup')

      return {
        success: true,
        redirectTo
      }
    } catch (err: any) {
      console.error('[useAuth] Login failed:', err)
      error.value = err?.data?.statusMessage || err?.message || 'Invalid email or password credentials.'
      await clearSessionContext()
      return {
        success: false,
        message: error.value
      }
    } finally {
      loading.value = false
    }
  }

  const logout = async () => {
    loading.value = true
    error.value = null
    try {
      await supabase.auth.signOut()
    } catch (err) {
      console.warn('[useAuth] Supabase sign out failed; clearing local session anyway.')
    } finally {
      await clearSessionContext()
      loading.value = false
      await navigateTo('/signin', { replace: true })
    }
  }

  return {
    loading: computed(() => loading.value),
    error: computed(() => error.value),
    initializeUserSession,
    clearSessionContext,
    cleanTokenString,
    signUp,
    signIn,
    logout
  }
}
