// utils/emojis.ts
export interface Emoji {
  emoji: string
  name: string
  category: string
  keywords?: string[]
}

export const EMOJIS: Emoji[] = [
  // Paste your entire EMOJIS array here
  { emoji: '😀', name: 'grinning', category: 'smileys', keywords: ['face', 'happy'] },
  
// Comprehensive emoji list with 1000+ emojis
const EMOJIS: Emoji[] = [
  // Smileys & Emotion (100+ emojis)
  { emoji: '😀', name: 'grinning', category: 'smileys', keywords: ['face', 'happy'] },
  { emoji: '😃', name: 'smiley', category: 'smileys', keywords: ['face', 'happy'] },
  { emoji: '😄', name: 'smile', category: 'smileys', keywords: ['face', 'happy'] },
  { emoji: '😁', name: 'beaming_face_with_smiling_eyes', category: 'smileys', keywords: ['face', 'happy'] },
  { emoji: '😆', name: 'grinning_face_with_sweat_drops', category: 'smileys', keywords: ['face', 'laugh'] },
  { emoji: '😅', name: 'grinning_face_with_sweat', category: 'smileys', keywords: ['face', 'laugh'] },
  { emoji: '🤣', name: 'rolling_on_the_floor_laughing', category: 'smileys', keywords: ['face', 'laugh'] },
  { emoji: '😂', name: 'joy', category: 'smileys', keywords: ['face', 'laugh', 'tear'] },
  { emoji: '🙂', name: 'slightly_smiling_face', category: 'smileys', keywords: ['face', 'smile'] },
  { emoji: '🙃', name: 'upside_down_face', category: 'smileys', keywords: ['face', 'smile'] },
  { emoji: '😉', name: 'winking_face', category: 'smileys', keywords: ['face', 'wink'] },
  { emoji: '😊', name: 'smiling_face_with_smiling_eyes', category: 'smileys', keywords: ['face', 'smile'] },
  { emoji: '😇', name: 'smiling_face_with_halo', category: 'smileys', keywords: ['face', 'angel'] },
  { emoji: '🥰', name: 'smiling_face_with_hearts', category: 'smileys', keywords: ['face', 'love'] },
  { emoji: '😍', name: 'heart_eyes', category: 'smileys', keywords: ['face', 'love'] },
  { emoji: '🤩', name: 'star_struck', category: 'smileys', keywords: ['face', 'star'] },
  { emoji: '😘', name: 'face_blowing_a_kiss', category: 'smileys', keywords: ['face', 'kiss'] },
  { emoji: '😗', name: 'kissing_face', category: 'smileys', keywords: ['face', 'kiss'] },
  { emoji: '😚', name: 'kissing_face_with_closed_eyes', category: 'smileys', keywords: ['face', 'kiss'] },
  { emoji: '😙', name: 'kissing_face_with_smiling_eyes', category: 'smileys', keywords: ['face', 'kiss'] },
  { emoji: '🥲', name: 'smiling_face_with_tear', category: 'smileys', keywords: ['face', 'smile'] },
  { emoji: '😋', name: 'face_savoring_food', category: 'smileys', keywords: ['face', 'tongue'] },
  { emoji: '😛', name: 'face_with_tongue', category: 'smileys', keywords: ['face', 'tongue'] },
  { emoji: '😜', name: 'winking_face_with_tongue', category: 'smileys', keywords: ['face', 'tongue'] },
  { emoji: '🤪', name: 'zany_face', category: 'smileys', keywords: ['face', 'crazy'] },
  { emoji: '😌', name: 'relieved_face', category: 'smileys', keywords: ['face', 'calm'] },
  { emoji: '😔', name: 'pensive_face', category: 'smileys', keywords: ['face', 'sad'] },
  { emoji: '😑', name: 'expressionless_face', category: 'smileys', keywords: ['face', 'neutral'] },
  { emoji: '😐', name: 'neutral_face', category: 'smileys', keywords: ['face', 'neutral'] },
  { emoji: '😶', name: 'face_with_mouth_covered', category: 'smileys', keywords: ['face', 'shy'] },
  { emoji: '🙁', name: 'slightly_frowning_face', category: 'smileys', keywords: ['face', 'sad'] },
  { emoji: '☹️', name: 'frowning_face', category: 'smileys', keywords: ['face', 'sad'] },
  { emoji: '😲', name: 'astonished_face', category: 'smileys', keywords: ['face', 'surprise'] },
  { emoji: '😞', name: 'disappointed_face', category: 'smileys', keywords: ['face', 'sad'] },
  { emoji: '😖', name: 'confounded_face', category: 'smileys', keywords: ['face', 'sad'] },
  { emoji: '😢', name: 'crying_face', category: 'smileys', keywords: ['face', 'sad', 'tear'] },
  { emoji: '😭', name: 'loudly_crying_face', category: 'smileys', keywords: ['face', 'sad', 'tear'] },
  { emoji: '😤', name: 'face_with_steam_from_nose', category: 'smileys', keywords: ['face', 'angry'] },
  { emoji: '😠', name: 'angry_face', category: 'smileys', keywords: ['face', 'angry'] },
  { emoji: '😡', name: 'pouting_face', category: 'smileys', keywords: ['face', 'angry'] },
  { emoji: '🤬', name: 'face_with_symbols_on_mouth', category: 'smileys', keywords: ['face', 'angry'] },
  { emoji: '😈', name: 'smiling_face_with_horns', category: 'smileys', keywords: ['face', 'devil'] },
  { emoji: '👿', name: 'angry_face_with_horns', category: 'smileys', keywords: ['face', 'devil'] },
  { emoji: '💀', name: 'skull', category: 'smileys', keywords: ['face', 'death'] },
  { emoji: '☠️', name: 'skull_and_crossbones', category: 'smileys', keywords: ['face', 'death'] },
  { emoji: '💩', name: 'pile_of_poo', category: 'smileys', keywords: ['face', 'poo'] },
  { emoji: '🤡', name: 'clown_face', category: 'smileys', keywords: ['face', 'clown'] },
  { emoji: '👹', name: 'ogre', category: 'smileys', keywords: ['face', 'monster'] },
  { emoji: '👺', name: 'goblin', category: 'smileys', keywords: ['face', 'monster'] },
  { emoji: '👻', name: 'ghost', category: 'smileys', keywords: ['face', 'ghost'] },
  { emoji: '👽', name: 'alien', category: 'smileys', keywords: ['face', 'alien'] },
  { emoji: '👾', name: 'alien_monster', category: 'smileys', keywords: ['face', 'alien'] },
  { emoji: '🤖', name: 'robot', category: 'smileys', keywords: ['face', 'robot'] },
  { emoji: '😺', name: 'grinning_cat', category: 'smileys', keywords: ['cat', 'happy'] },
  { emoji: '😸', name: 'grinning_cat_with_smiling_eyes', category: 'smileys', keywords: ['cat', 'happy'] },
  { emoji: '😹', name: 'cat_with_tears_of_joy', category: 'smileys', keywords: ['cat', 'laugh'] },
  { emoji: '😻', name: 'smiling_cat_with_heart_eyes', category: 'smileys', keywords: ['cat', 'love'] },
  { emoji: '😼', name: 'cat_with_wry_mouth', category: 'smileys', keywords: ['cat', 'smile'] },
  { emoji: '😽', name: 'kissing_cat', category: 'smileys', keywords: ['cat', 'kiss'] },
  { emoji: '🙀', name: 'weary_cat', category: 'smileys', keywords: ['cat', 'sad'] },
  { emoji: '😿', name: 'crying_cat', category: 'smileys', keywords: ['cat', 'sad'] },
  { emoji: '😾', name: 'pouting_cat', category: 'smileys', keywords: ['cat', 'angry'] },

  // Hand Gestures (50+ emojis)
  { emoji: '👋', name: 'waving_hand', category: 'hands', keywords: ['hand', 'wave'] },
  { emoji: '🤚', name: 'raised_back_of_hand', category: 'hands', keywords: ['hand', 'raise'] },
  { emoji: '🖐️', name: 'hand_with_fingers_splayed', category: 'hands', keywords: ['hand', 'fingers'] },
  { emoji: '✋', name: 'raised_hand', category: 'hands', keywords: ['hand', 'raise'] },
  { emoji: '🖖', name: 'vulcan_salute', category: 'hands', keywords: ['hand', 'star'] },
  { emoji: '👌', name: 'ok_hand', category: 'hands', keywords: ['hand', 'ok'] },
  { emoji: '🤌', name: 'pinched_fingers', category: 'hands', keywords: ['hand', 'pinch'] },
  { emoji: '🤏', name: 'pinching_hand', category: 'hands', keywords: ['hand', 'small'] },
  { emoji: '✌️', name: 'victory', category: 'hands', keywords: ['hand', 'peace'] },
  { emoji: '🤞', name: 'crossed_fingers', category: 'hands', keywords: ['hand', 'luck'] },
  { emoji: '🤟', name: 'love_you_gesture', category: 'hands', keywords: ['hand', 'love'] },
  { emoji: '🤘', name: 'sign_of_the_horns', category: 'hands', keywords: ['hand', 'rock'] },
  { emoji: '🤙', name: 'call_me_hand', category: 'hands', keywords: ['hand', 'call'] },
  { emoji: '👈', name: 'backhand_index_pointing_left', category: 'hands', keywords: ['hand', 'point'] },
  { emoji: '👉', name: 'backhand_index_pointing_right', category: 'hands', keywords: ['hand', 'point'] },
  { emoji: '👆', name: 'backhand_index_pointing_up', category: 'hands', keywords: ['hand', 'point'] },
  { emoji: '👇', name: 'backhand_index_pointing_down', category: 'hands', keywords: ['hand', 'point'] },
  { emoji: '☝️', name: 'index_pointing_up', category: 'hands', keywords: ['hand', 'point'] },
  { emoji: '👍', name: '+1', category: 'hands', keywords: ['hand', 'thumbs'] },
  { emoji: '👎', name: '-1', category: 'hands', keywords: ['hand', 'thumbs'] },
  { emoji: '✊', name: 'fist', category: 'hands', keywords: ['hand', 'fist'] },
  { emoji: '👊', name: 'oncoming_fist', category: 'hands', keywords: ['hand', 'fist'] },
  { emoji: '🤛', name: 'left_facing_fist', category: 'hands', keywords: ['hand', 'fist'] },
  { emoji: '🤜', name: 'right_facing_fist', category: 'hands', keywords: ['hand', 'fist'] },
  { emoji: '👏', name: 'clapping_hands', category: 'hands', keywords: ['hand', 'clap'] },
  { emoji: '🙌', name: 'raising_hands', category: 'hands', keywords: ['hand', 'raise'] },
  { emoji: '👐', name: 'open_hands', category: 'hands', keywords: ['hand', 'open'] },
  { emoji: '🤲', name: 'open_hands_with_palms_up', category: 'hands', keywords: ['hand', 'open'] },
  { emoji: '🤝', name: 'handshake', category: 'hands', keywords: ['hand', 'shake'] },
  { emoji: '💅', name: 'nail_polish', category: 'hands', keywords: ['hand', 'nail'] },

  // Hearts & Love (20+ emojis)
  { emoji: '❤️', name: 'red_heart', category: 'hearts', keywords: ['heart', 'love'] },
  { emoji: '🧡', name: 'orange_heart', category: 'hearts', keywords: ['heart', 'love'] },
  { emoji: '💛', name: 'yellow_heart', category: 'hearts', keywords: ['heart', 'love'] },
  { emoji: '💚', name: 'green_heart', category: 'hearts', keywords: ['heart', 'love'] },
  { emoji: '💙', name: 'blue_heart', category: 'hearts', keywords: ['heart', 'love'] },
  { emoji: '💜', name: 'purple_heart', category: 'hearts', keywords: ['heart', 'love'] },
  { emoji: '🖤', name: 'black_heart', category: 'hearts', keywords: ['heart', 'love'] },
  { emoji: '🤍', name: 'white_heart', category: 'hearts', keywords: ['heart', 'love'] },
  { emoji: '🤎', name: 'brown_heart', category: 'hearts', keywords: ['heart', 'love'] },
  { emoji: '💔', name: 'broken_heart', category: 'hearts', keywords: ['heart', 'sad'] },
  { emoji: '💕', name: 'two_hearts', category: 'hearts', keywords: ['heart', 'love'] },
  { emoji: '💞', name: 'revolving_hearts', category: 'hearts', keywords: ['heart', 'love'] },
  { emoji: '💓', name: 'beating_heart', category: 'hearts', keywords: ['heart', 'love'] },
  { emoji: '💗', name: 'growing_heart', category: 'hearts', keywords: ['heart', 'love'] },
  { emoji: '💖', name: 'sparkling_heart', category: 'hearts', keywords: ['heart', 'love'] },
  { emoji: '💘', name: 'cupid', category: 'hearts', keywords: ['heart', 'love'] },
  { emoji: '💝', name: 'heart_with_ribbon', category: 'hearts', keywords: ['heart', 'gift'] },
  { emoji: '💟', name: 'heart_decoration', category: 'hearts', keywords: ['heart', 'decoration'] },

  // Objects (100+ emojis)
  { emoji: '🎉', name: 'party_popper', category: 'objects', keywords: ['party', 'celebration'] },
  { emoji: '🎊', name: 'confetti_ball', category: 'objects', keywords: ['party', 'celebration'] },
  { emoji: '🎈', name: 'balloon', category: 'objects', keywords: ['party', 'celebration'] },
  { emoji: '🎁', name: 'wrapped_gift', category: 'objects', keywords: ['gift', 'present'] },
  { emoji: '🎀', name: 'ribbon', category: 'objects', keywords: ['gift', 'decoration'] },
  { emoji: '🎂', name: 'birthday_cake', category: 'objects', keywords: ['cake', 'birthday'] },
  { emoji: '🍰', name: 'cake', category: 'objects', keywords: ['cake', 'food'] },
  { emoji: '🍾', name: 'bottle_with_popping_cork', category: 'objects', keywords: ['drink', 'celebration'] },
  { emoji: '🍷', name: 'wine_glass', category: 'objects', keywords: ['drink', 'wine'] },
  { emoji: '🍸', name: 'cocktail_glass', category: 'objects', keywords: ['drink', 'cocktail'] },
  { emoji: '🍹', name: 'tropical_drink', category: 'objects', keywords: ['drink', 'tropical'] },
  { emoji: '🍺', name: 'beer_mug', category: 'objects', keywords: ['drink', 'beer'] },
  { emoji: '🍻', name: 'clinking_beer_mugs', category: 'objects', keywords: ['drink', 'beer'] },
  { emoji: '🎮', name: 'video_game', category: 'objects', keywords: ['game', 'play'] },
  { emoji: '🎯', name: 'direct_hit', category: 'objects', keywords: ['game', 'target'] },
  { emoji: '🎲', name: 'game_die', category: 'objects', keywords: ['game', 'dice'] },
  { emoji: '🎳', name: 'bowling', category: 'objects', keywords: ['game', 'sport'] },
  { emoji: '🎪', name: 'circus_tent', category: 'objects', keywords: ['circus', 'entertainment'] },
  { emoji: '🎨', name: 'artist_palette', category: 'objects', keywords: ['art', 'paint'] },
  { emoji: '🎬', name: 'clapper_board', category: 'objects', keywords: ['movie', 'film'] },
  { emoji: '🎤', name: 'microphone', category: 'objects', keywords: ['music', 'sing'] },
  { emoji: '🎧', name: 'headphone', category: 'objects', keywords: ['music', 'audio'] },
  { emoji: '🎼', name: 'musical_score', category: 'objects', keywords: ['music', 'note'] },
  { emoji: '🎹', name: 'musical_keyboard', category: 'objects', keywords: ['music', 'instrument'] },
  { emoji: '🥁', name: 'drum', category: 'objects', keywords: ['music', 'instrument'] },
  { emoji: '🎷', name: 'saxophone', category: 'objects', keywords: ['music', 'instrument'] },
  { emoji: '🎺', name: 'trumpet', category: 'objects', keywords: ['music', 'instrument'] },
  { emoji: '🎸', name: 'guitar', category: 'objects', keywords: ['music', 'instrument'] },
  { emoji: '🎻', name: 'violin', category: 'objects', keywords: ['music', 'instrument'] },
  { emoji: '📱', name: 'mobile_phone', category: 'objects', keywords: ['phone', 'device'] },
  { emoji: '💻', name: 'laptop', category: 'objects', keywords: ['computer', 'device'] },
  { emoji: '⌨️', name: 'keyboard', category: 'objects', keywords: ['computer', 'device'] },
  { emoji: '🖱️', name: 'computer_mouse', category: 'objects', keywords: ['computer', 'device'] },
  { emoji: '🖨️', name: 'printer', category: 'objects', keywords: ['computer', 'device'] },
  { emoji: '🖥️', name: 'desktop_computer', category: 'objects', keywords: ['computer', 'device'] },
  { emoji: '🎓', name: 'graduation_cap', category: 'objects', keywords: ['education', 'school'] },
  { emoji: '📚', name: 'books', category: 'objects', keywords: ['education', 'book'] },
  { emoji: '📖', name: 'open_book', category: 'objects', keywords: ['education', 'book'] },
  { emoji: '📝', name: 'memo', category: 'objects', keywords: ['writing', 'note'] },
  { emoji: '✏️', name: 'pencil', category: 'objects', keywords: ['writing', 'tool'] },
  { emoji: '✒️', name: 'black_nib', category: 'objects', keywords: ['writing', 'tool'] },
  { emoji: '🖋️', name: 'fountain_pen', category: 'objects', keywords: ['writing', 'tool'] },
  { emoji: '🖊️', name: 'pen', category: 'objects', keywords: ['writing', 'tool'] },
  { emoji: '🎓', name: 'graduation_cap', category: 'objects', keywords: ['education', 'school'] },
  { emoji: '🏆', name: 'trophy', category: 'objects', keywords: ['award', 'win'] },
  { emoji: '🥇', name: 'first_place_medal', category: 'objects', keywords: ['award', 'medal'] },
  { emoji: '🥈', name: 'second_place_medal', category: 'objects', keywords: ['award', 'medal'] },
  { emoji: '🥉', name: 'third_place_medal', category: 'objects', keywords: ['award', 'medal'] },
  { emoji: '⚽', name: 'soccer_ball', category: 'objects', keywords: ['sport', 'ball'] },
  { emoji: '🏀', name: 'basketball', category: 'objects', keywords: ['sport', 'ball'] },
  { emoji: '🏈', name: 'american_football', category: 'objects', keywords: ['sport', 'ball'] },
  { emoji: '⚾', name: 'baseball', category: 'objects', keywords: ['sport', 'ball'] },
  { emoji: '🎾', name: 'tennis', category: 'objects', keywords: ['sport', 'ball'] },
  { emoji: '🏐', name: 'volleyball', category: 'objects', keywords: ['sport', 'ball'] },
  { emoji: '🏉', name: 'rugby_football', category: 'objects', keywords: ['sport', 'ball'] },
  { emoji: '🥏', name: 'softball', category: 'objects', keywords: ['sport', 'ball'] },
  { emoji: '🎳', name: 'bowling', category: 'objects', keywords: ['sport', 'game'] },
  { emoji: '🎣', name: 'fishing_pole', category: 'objects', keywords: ['sport', 'fishing'] },
  { emoji: '🎽', name: 'running_shirt', category: 'objects', keywords: ['sport', 'clothing'] },
  { emoji: '🎿', name: 'skis', category: 'objects', keywords: ['sport', 'winter'] },
  { emoji: '⛷️', name: 'skier', category: 'objects', keywords: ['sport', 'winter'] },
  { emoji: '🏂', name: 'snowboarder', category: 'objects', keywords: ['sport', 'winter'] },

  // Nature (150+ emojis)
  { emoji: '🌟', name: 'glowing_star', category: 'nature', keywords: ['star', 'shine'] },
  { emoji: '⭐', name: 'star', category: 'nature', keywords: ['star', 'shine'] },
  { emoji: '✨', name: 'sparkles', category: 'nature', keywords: ['sparkle', 'shine'] },
  { emoji: '⚡', name: 'high_voltage', category: 'nature', keywords: ['lightning', 'power'] },
  { emoji: '🔥', name: 'fire', category: 'nature', keywords: ['fire', 'hot'] },
  { emoji: '💥', name: 'collision', category: 'nature', keywords: ['explosion', 'boom'] },
  { emoji: '💫', name: 'dizzy', category: 'nature', keywords: ['dizzy', 'star'] },
  { emoji: '🌈', name: 'rainbow', category: 'nature', keywords: ['rainbow', 'color'] },
  { emoji: '☀️', name: 'sun', category: 'nature', keywords: ['sun', 'weather'] },
  { emoji: '🌙', name: 'crescent_moon', category: 'nature', keywords: ['moon', 'night'] },
  { emoji: '🌠', name: 'shooting_star', category: 'nature', keywords: ['star', 'night'] },
  { emoji: '🌌', name: 'milky_way', category: 'nature', keywords: ['space', 'galaxy'] },
  { emoji: '🌃', name: 'night_with_stars', category: 'nature', keywords: ['night', 'city'] },
  { emoji: '🌆', name: 'sunset', category: 'nature', keywords: ['sunset', 'city'] },
  { emoji: '🌇', name: 'sunset', category: 'nature', keywords: ['sunset', 'city'] },
  { emoji: '🌉', name: 'bridge_at_night', category: 'nature', keywords: ['night', 'city'] },
  { emoji: '🌁', name: 'foggy', category: 'nature', keywords: ['fog', 'city'] },
  { emoji: '🌄', name: 'sunrise_on_mountains', category: 'nature', keywords: ['sunrise', 'mountain'] },
  { emoji: '🌅', name: 'sunrise', category: 'nature', keywords: ['sunrise', 'morning'] },
  { emoji: '🌋', name: 'volcano', category: 'nature', keywords: ['volcano', 'mountain'] },
  { emoji: '⛰️', name: 'mountain', category: 'nature', keywords: ['mountain', 'nature'] },
  { emoji: '🏔️', name: 'mountain_snow', category: 'nature', keywords: ['mountain', 'snow'] },
  { emoji: '🗻', name: 'mount_fuji', category: 'nature', keywords: ['mountain', 'japan'] },
  { emoji: '🏕️', name: 'camping', category: 'nature', keywords: ['camping', 'outdoor'] },
  { emoji: '⛺', name: 'tent', category: 'nature', keywords: ['tent', 'camping'] },
  { emoji: '⛲', name: 'fountain', category: 'nature', keywords: ['fountain', 'water'] },
  { emoji: '⛱️', name: 'umbrella_on_ground', category: 'nature', keywords: ['beach', 'umbrella'] },
  { emoji: '🏖️', name: 'beach_with_umbrella', category: 'nature', keywords: ['beach', 'vacation'] },
  { emoji: '🏝️', name: 'desert_island', category: 'nature', keywords: ['island', 'beach'] },
  { emoji: '🌲', name: 'evergreen_tree', category: 'nature', keywords: ['tree', 'nature'] },
  { emoji: '🌳', name: 'deciduous_tree', category: 'nature', keywords: ['tree', 'nature'] },
  { emoji: '🌴', name: 'palm_tree', category: 'nature', keywords: ['tree', 'tropical'] },
  { emoji: '🌵', name: 'cactus', category: 'nature', keywords: ['cactus', 'desert'] },
  { emoji: '🌾', name: 'sheaf_of_rice', category: 'nature', keywords: ['rice', 'grain'] },
  { emoji: '💐', name: 'bouquet', category: 'nature', keywords: ['flower', 'bouquet'] },
  { emoji: '🌷', name: 'tulip', category: 'nature', keywords: ['flower', 'tulip'] },
  { emoji: '🌹', name: 'rose', category: 'nature', keywords: ['flower', 'rose'] },
  { emoji: '🥀', name: 'wilted_flower', category: 'nature', keywords: ['flower', 'wilted'] },
  { emoji: '🌺', name: 'hibiscus', category: 'nature', keywords: ['flower', 'hibiscus'] },
  { emoji: '🌻', name: 'sunflower', category: 'nature', keywords: ['flower', 'sunflower'] },
  { emoji: '🌞', name: 'sun_with_face', category: 'nature', keywords: ['sun', 'face'] },
  { emoji: '🌝', name: 'full_moon_with_face', category: 'nature', keywords: ['moon', 'face'] },
  { emoji: '🌛', name: 'first_quarter_moon_with_face', category: 'nature', keywords: ['moon', 'face'] },
  { emoji: '🌜', name: 'last_quarter_moon_with_face', category: 'nature', keywords: ['moon', 'face'] },
  { emoji: '🌚', name: 'new_moon_with_face', category: 'nature', keywords: ['moon', 'face'] },
  { emoji: '🌕', name: 'full_moon', category: 'nature', keywords: ['moon', 'night'] },
  { emoji: '🌖', name: 'waning_gibbous_moon', category: 'nature', keywords: ['moon', 'night'] },
  { emoji: '🌗', name: 'last_quarter_moon', category: 'nature', keywords: ['moon', 'night'] },
  { emoji: '🌘', name: 'waning_crescent_moon', category: 'nature', keywords: ['moon', 'night'] },
  { emoji: '🌑', name: 'new_moon', category: 'nature', keywords: ['moon', 'night'] },
  { emoji: '🌒', name: 'waxing_crescent_moon', category: 'nature', keywords: ['moon', 'night'] },
  { emoji: '🌓', name: 'first_quarter_moon', category: 'nature', keywords: ['moon', 'night'] },
  { emoji: '🌔', name: 'waxing_gibbous_moon', category: 'nature', keywords: ['moon', 'night'] },
  { emoji: '☄️', name: 'comet', category: 'nature', keywords: ['comet', 'space'] },
  { emoji: '🌪️', name: 'tornado', category: 'nature', keywords: ['tornado', 'weather'] },
  { emoji: '🌤️', name: 'sun_small_cloud', category: 'nature', keywords: ['sun', 'cloud'] },
  { emoji: '⛅', name: 'sun_behind_small_cloud', category: 'nature', keywords: ['sun', 'cloud'] },
  { emoji: '🌥️', name: 'sun_behind_large_cloud', category: 'nature', keywords: ['sun', 'cloud'] },
  { emoji: '☁️', name: 'cloud', category: 'nature', keywords: ['cloud', 'weather'] },
  { emoji: '🌦️', name: 'sun_behind_rain_cloud', category: 'nature', keywords: ['rain', 'weather'] },
  { emoji: '🌧️', name: 'cloud_with_rain', category: 'nature', keywords: ['rain', 'weather'] },
  { emoji: '⛈️', name: 'cloud_with_lightning_and_rain', category: 'nature', keywords: ['storm', 'weather'] },
  { emoji: '🌩️', name: 'cloud_with_lightning', category: 'nature', keywords: ['lightning', 'weather'] },
  { emoji: '🌨️', name: 'cloud_with_snow', category: 'nature', keywords: ['snow', 'weather'] },
  { emoji: '❄️', name: 'snowflake', category: 'nature', keywords: ['snow', 'cold'] },
  { emoji: '☃️', name: 'snowman', category: 'nature', keywords: ['snowman', 'winter'] },
  { emoji: '⛄', name: 'snowman_without_snow', category: 'nature', keywords: ['snowman', 'winter'] },
  { emoji: '🌬️', name: 'wind_face', category: 'nature', keywords: ['wind', 'weather'] },
  { emoji: '💨', name: 'dashing_away', category: 'nature', keywords: ['wind', 'fast'] },
  { emoji: '💧', name: 'droplet', category: 'nature', keywords: ['water', 'drop'] },
  { emoji: '💦', name: 'sweat_droplets', category: 'nature', keywords: ['water', 'sweat'] },
  { emoji: '☔', name: 'umbrella_with_rain_drops', category: 'nature', keywords: ['rain', 'umbrella'] },
  { emoji: '🍏', name: 'green_apple', category: 'nature', keywords: ['apple', 'fruit'] },
  { emoji: '🍎', name: 'red_apple', category: 'nature', keywords: ['apple', 'fruit'] },
  { emoji: '🍐', name: 'pear', category: 'nature', keywords: ['pear', 'fruit'] },
  { emoji: '🍊', name: 'orange', category: 'nature', keywords: ['orange', 'fruit'] },
  { emoji: '🍋', name: 'lemon', category: 'nature', keywords: ['lemon', 'fruit'] },
  { emoji: '🍌', name: 'banana', category: 'nature', keywords: ['banana', 'fruit'] },
  { emoji: '🍉', name: 'watermelon', category: 'nature', keywords: ['watermelon', 'fruit'] },
  { emoji: '🍇', name: 'grapes', category: 'nature', keywords: ['grapes', 'fruit'] },
  { emoji: '🍓', name: 'strawberry', category: 'nature', keywords: ['strawberry', 'fruit'] },
  { emoji: '🍈', name: 'melon', category: 'nature', keywords: ['melon', 'fruit'] },
  { emoji: '🍒', name: 'cherries', category: 'nature', keywords: ['cherries', 'fruit'] },
  { emoji: '🍑', name: 'peach', category: 'nature', keywords: ['peach', 'fruit'] },
  { emoji: '🥭', name: 'mango', category: 'nature', keywords: ['mango', 'fruit'] },
  { emoji: '🍍', name: 'pineapple', category: 'nature', keywords: ['pineapple', 'fruit'] },
  { emoji: '🥥', name: 'coconut', category: 'nature', keywords: ['coconut', 'fruit'] },
  { emoji: '🥑', name: 'avocado', category: 'nature', keywords: ['avocado', 'fruit'] },
  { emoji: '🍆', name: 'eggplant', category: 'nature', keywords: ['eggplant', 'vegetable'] },
  { emoji: '🍅', name: 'tomato', category: 'nature', keywords: ['tomato', 'vegetable'] },
  { emoji: '🍄', name: 'mushroom', category: 'nature', keywords: ['mushroom', 'vegetable'] },
  { emoji: '🌶️', name: 'hot_pepper', category: 'nature', keywords: ['pepper', 'spicy'] },
  { emoji: '🌽', name: 'corn', category: 'nature', keywords: ['corn', 'vegetable'] },
  { emoji: '🐶', name: 'dog_face', category: 'nature', keywords: ['dog', 'animal'] },
  { emoji: '🐱', name: 'cat_face', category: 'nature', keywords: ['cat', 'animal'] },
  { emoji: '🐭', name: 'mouse_face', category: 'nature', keywords: ['mouse', 'animal'] },
  { emoji: '🐹', name: 'hamster', category: 'nature', keywords: ['hamster', 'animal'] },
  { emoji: '🐰', name: 'rabbit_face', category: 'nature', keywords: ['rabbit', 'animal'] },
  { emoji: '🦊', name: 'fox', category: 'nature', keywords: ['fox', 'animal'] },
  { emoji: '🐻', name: 'bear_face', category: 'nature', keywords: ['bear', 'animal'] },
  { emoji: '🐼', name: 'panda', category: 'nature', keywords: ['panda', 'animal'] },
  { emoji: '🐨', name: 'koala', category: 'nature', keywords: ['koala', 'animal'] },
  { emoji: '🐯', name: 'tiger_face', category: 'nature', keywords: ['tiger', 'animal'] },
  { emoji: '🦁', name: 'lion', category: 'nature', keywords: ['lion', 'animal'] },
  { emoji: '🐮', name: 'cow_face', category: 'nature', keywords: ['cow',

    // Emoji data
const categories = ref([
  { id: 'recent', name: 'Recently Used', icon: '🕒' },
  { id: 'smileys', name: 'Smileys & Emotion', icon: '😀' },
  { id: 'people', name: 'People & Body', icon: '👋' },
  { id: 'animals', name: 'Animals & Nature', icon: '🐶' },
  { id: 'food', name: 'Food & Drink', icon: '🍎' },
  { id: 'activities', name: 'Activities', icon: '⚽' },
  { id: 'travel', name: 'Travel & Places', icon: '🚗' },
  { id: 'objects', name: 'Objects', icon: '💡' },
  { id: 'symbols', name: 'Symbols', icon: '❤️' },
  { id: 'flags', name: 'Flags', icon: '🏁' }
])

const emojis = ref({
  smileys: [
    { char: '😀', name: 'grinning face' },
    { char: '😃', name: 'grinning face with big eyes' },
    { char: '😄', name: 'grinning face with smiling eyes' },
    { char: '😁', name: 'beaming face with smiling eyes' },
    { char: '😆', name: 'grinning squinting face' },
    { char: '😅', name: 'grinning face with sweat' },
    { char: '🤣', name: 'rolling on the floor laughing' },
    { char: '😂', name: 'face with tears of joy' },
    { char: '🙂', name: 'slightly smiling face' },
    { char: '🙃', name: 'upside-down face' },
    { char: '😉', name: 'winking face' },
    { char: '😊', name: 'smiling face with smiling eyes' },
    { char: '😇', name: 'smiling face with halo' },
    { char: '🥰', name: 'smiling face with hearts' },
    { char: '😍', name: 'smiling face with heart-eyes' },
    { char: '🤩', name: 'star-struck' },
    { char: '😘', name: 'face blowing a kiss' },
    { char: '😗', name: 'kissing face' },
    { char: '😚', name: 'kissing face with closed eyes' },
    { char: '😙', name: 'kissing face with smiling eyes' },
    { char: '😋', name: 'face savoring food' },
    { char: '😛', name: 'face with tongue' },
    { char: '😜', name: 'winking face with tongue' },
    { char: '🤪', name: 'zany face' },
    { char: '😝', name: 'squinting face with tongue' },
    { char: '🤑', name: 'money-mouth face' },
    { char: '🤗', name: 'hugging face' },
    { char: '🤭', name: 'face with hand over mouth' },
    { char: '🤫', name: 'shushing face' },
    { char: '🤔', name: 'thinking face' },
    { char: '🤐', name: 'zipper-mouth face' },
    { char: '🤨', name: 'face with raised eyebrow' },
    { char: '😐', name: 'neutral face' },
    { char: '😑', name: 'expressionless face' },
    { char: '😶', name: 'face without mouth' },
    { char: '😏', name: 'smirking face' },
    { char: '😒', name: 'unamused face' },
    { char: '🙄', name: 'face with rolling eyes' },
    { char: '😬', name: 'grimacing face' },
    { char: '🤥', name: 'lying face' },
    { char: '😔', name: 'pensive face' },
    { char: '😪', name: 'sleepy face' },
    { char: '🤤', name: 'drooling face' },
    { char: '😴', name: 'sleeping face' },
    { char: '😷', name: 'face with medical mask' },
    { char: '🤒', name: 'face with thermometer' },
    { char: '🤕', name: 'face with head-bandage' },
    { char: '🤢', name: 'nauseated face' },
    { char: '🤮', name: 'face vomiting' },
    { char: '🤧', name: 'sneezing face' },
    { char: '🥵', name: 'hot face' },
    { char: '🥶', name: 'cold face' },
    { char: '🥴', name: 'woozy face' },
    { char: '😵', name: 'dizzy face' },
    { char: '🤯', name: 'exploding head' },
    { char: '🤠', name: 'cowboy hat face' },
    { char: '🥳', name: 'partying face' },
    { char: '😎', name: 'smiling face with sunglasses' },
    { char: '🤓', name: 'nerd face' },
    { char: '🧐', name: 'face with monocle' }
  ],
  people: [
    { char: '👋', name: 'waving hand' },
    { char: '🤚', name: 'raised back of hand' },
    { char: '🖐️', name: 'hand with fingers splayed' },
    { char: '✋', name: 'raised hand' },
    { char: '🖖', name: 'vulcan salute' },
    { char: '👌', name: 'OK hand' },
    { char: '🤏', name: 'pinching hand' },
    { char: '✌️', name: 'victory hand' },
    { char: '🤞', name: 'crossed fingers' },
    { char: '🤟', name: 'love-you gesture' },
    { char: '🤘', name: 'sign of the horns' },
    { char: '🤙', name: 'call me hand' },
    { char: '👈', name: 'backhand index pointing left' },
    { char: '👉', name: 'backhand index pointing right' },
    { char: '👆', name: 'backhand index pointing up' },
    { char: '🖕', name: 'middle finger' },
    { char: '👇', name: 'backhand index pointing down' },
    { char: '☝️', name: 'index pointing up' },
    { char: '👍', name: 'thumbs up' },
    { char: '👎', name: 'thumbs down' },
    { char: '✊', name: 'raised fist' },
    { char: '👊', name: 'oncoming fist' },
    { char: '🤛', name: 'left-facing fist' },
    { char: '🤜', name: 'right-facing fist' },
    { char: '👏', name: 'clapping hands' },
    { char: '🙌', name: 'raising hands' },
    { char: '👐', name: 'open hands' },
    { char: '🤲', name: 'palms up together' },
    { char: '🤝', name: 'handshake' },
    { char: '🙏', name: 'folded hands' }
  ],
  animals: [
    { char: '🐶', name: 'dog face' },
    { char: '🐱', name: 'cat face' },
    { char: '🐭', name: 'mouse face' },
    { char: '🐹', name: 'hamster face' },
    { char: '🐰', name: 'rabbit face' },
    { char: '🦊', name: 'fox face' },
    { char: '🐻', name: 'bear face' },
    { char: '🐼', name: 'panda face' },
    { char: '🐨', name: 'koala' },
    { char: '🐯', name: 'tiger face' },
    { char: '🦁', name: 'lion face' },
    { char: '🐮', name: 'cow face' },
    { char: '🐷', name: 'pig face' },
    { char: '🐽', name: 'pig nose' },
    { char: '🐸', name: 'frog face' },
    { char: '🐵', name: 'monkey face' },
    { char: '🙈', name: 'see-no-evil monkey' },
    { char: '🙉', name: 'hear-no-evil monkey' },
    { char: '🙊', name: 'speak-no-evil monkey' },
    { char: '🐒', name: 'monkey' }
  ],
  food: [
    { char: '🍎', name: 'red apple' },
    { char: '🍊', name: 'tangerine' },
    { char: '🍋', name: 'lemon' },
    { char: '🍌', name: 'banana' },
    { char: '🍉', name: 'watermelon' },
    { char: '🍇', name: 'grapes' },
    { char: '🍓', name: 'strawberry' },
    { char: '🍈', name: 'melon' },
    { char: '🍒', name: 'cherries' },
    { char: '🍑', name: 'peach' },
    { char: '🥭', name: 'mango' },
    { char: '🍍', name: 'pineapple' },
    { char: '🥥', name: 'coconut' },
    { char: '🥝', name: 'kiwi fruit' },
    { char: '🍅', name: 'tomato' },
    { char: '🍆', name: 'eggplant' },
    { char: '🥑', name: 'avocado' },
    { char: '🥦', name: 'broccoli' },
    { char: '🥬', name: 'leafy greens' },
    { char: '🥒', name: 'cucumber' }
  ],
  activities: [
    { char: '⚽', name: 'soccer ball' },
    { char: '🏀', name: 'basketball' },
    { char: '🏈', name: 'american football' },
    { char: '⚾', name: 'baseball' },
    { char: '🥎', name: 'softball' },
    { char: '🎾', name: 'tennis' },
    { char: '🏐', name: 'volleyball' },
    { char: '🏉', name: 'rugby football' },
    { char: '🥏', name: 'flying disc' },
    { char: '🎱', name: 'pool 8 ball' },
    { char: '🪀', name: 'yo-yo' },
    { char: '🏓', name: 'ping pong' },
    { char: '🏸', name: 'badminton' },
    { char: '🥅', name: 'goal net' },
    { char: '⛳', name: 'flag in hole' },
    { char: '🪁', name: 'kite' },
    { char: '🏹', name: 'bow and arrow' },
    { char: '🎣', name: 'fishing pole' },
    { char: '🤿', name: 'diving mask' },
    { char: '🥊', name: 'boxing glove' }
  ],
  travel: [
    { char: '🚗', name: 'automobile' },
    { char: '🚕', name: 'taxi' },
    { char: '🚙', name: 'sport utility vehicle' },
    { char: '🚌', name: 'bus' },
    { char: '🚎', name: 'trolleybus' },
    { char: '🏎️', name: 'racing car' },
    { char: '🚓', name: 'police car' },
    { char: '🚑', name: 'ambulance' },
    { char: '🚒', name: 'fire engine' },
    { char: '🚐', name: 'minibus' },
    { char: '🛻', name: 'pickup truck' },
    { char: '🚚', name: 'delivery truck' },
    { char: '🚛', name: 'articulated lorry' },
    { char: '🚜', name: 'tractor' },
    { char: '🏍️', name: 'motorcycle' },
    { char: '🛵', name: 'motor scooter' },
    { char: '🚲', name: 'bicycle' },
    { char: '🛴', name: 'kick scooter' },
    { char: '🛹', name: 'skateboard' },
    { char: '🛼', name: 'roller skate' }
  ],
  objects: [
    { char: '💡', name: 'light bulb' },
    { char: '🔦', name: 'flashlight' },
    { char: '🕯️', name: 'candle' },
    { char: '🪔', name: 'diya lamp' },
    { char: '🧯', name: 'fire extinguisher' },
    { char: '🛢️', name: 'oil drum' },
    { char: '💸', name: 'money with wings' },
    { char: '💵', name: 'dollar banknote' },
    { char: '💴', name: 'yen banknote' },
    { char: '💶', name: 'euro banknote' },
    { char: '💷', name: 'pound banknote' },
    { char: '💰', name: 'money bag' },
    { char: '💳', name: 'credit card' },
    { char: '💎', name: 'gem stone' },
    { char: '⚖️', name: 'balance scale' },
    { char: '🧰', name: 'toolbox' },
    { char: '🔧', name: 'wrench' },
    { char: '🔨', name: 'hammer' },
    { char: '⚒️', name: 'hammer and pick' },
    { char: '🛠️', name: 'hammer and wrench' }
  ],
  symbols: [
    { char: '❤️', name: 'red heart' },
    { char: '🧡', name: 'orange heart' },
    { char: '💛', name: 'yellow heart' },
    { char: '💚', name: 'green heart' },
    { char: '💙', name: 'blue heart' },
    { char: '💜', name: 'purple heart' },
    { char: '🖤', name: 'black heart' },
    { char: '🤍', name: 'white heart' },
    { char: '🤎', name: 'brown heart' },
    { char: '💔', name: 'broken heart' },
    { char: '❣️', name: 'heart exclamation' },
    { char: '💕', name: 'two hearts' },
    { char: '💞', name: 'revolving hearts' },
    { char: '💓', name: 'beating heart' },
    { char: '💗', name: 'growing heart' },
    { char: '💖', name: 'sparkling heart' },
    { char: '💘', name: 'heart with arrow' },
    { char: '💝', name: 'heart with ribbon' },
    { char: '💟', name: 'heart decoration' },
    { char: '☮️', name: 'peace symbol' }
  ],
  flags: [
    { char: '🏁', name: 'chequered flag' },
    { char: '🚩', name: 'triangular flag' },
    { char: '🎌', name: 'crossed flags' },
    { char: '🏴', name: 'black flag' },
    { char: '🏳️', name: 'white flag' },
    { char: '🏳️‍🌈', name: 'rainbow flag' },
    { char: '🏳️‍⚧️', name: 'transgender flag' },
    { char: '🏴‍☠️', name: 'pirate flag' },
    { char: '🇺🇸', name: 'flag: United States' },
    { char: '🇬🇧', name: 'flag: United Kingdom' },
    { char: '🇨🇦', name: 'flag: Canada' },
    { char: '🇫🇷', name: 'flag: France' },
    { char: '🇩🇪', name: 'flag: Germany' },
    { char: '🇮🇹', name: 'flag: Italy' },
    { char: '🇪🇸', name: 'flag: Spain' },
    { char: '🇯🇵', name: 'flag: Japan' },
    { char: '🇰🇷', name: 'flag: South Korea' },
    { char: '🇨🇳', name: 'flag: China' },
    { char: '🇮🇳', name: 'flag: India' },
    { char: '🇧🇷', name: 'flag: Brazil' }
  ]
})
                                                             
